# Nome da aplicação
spring.application.name=api-soema

spring.datasource.url=jdbc:mysql://localhost:3307/soema_db
spring.datasource.username=root
spring.datasource.password=minhaSenha123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Porta e endereço do servidor
server.port=9090
server.address=0.0.0.0


